[package]
name = "wednesday-vm"
version = "0.1.0"
edition = "2024"
license = "MIT"
description = "A purpose-built virtual machine for the Wednesday language."
homepage = "https://github.com/windows-fryer/wednesday-oxidize"
repository = "https://github.com/windows-fryer/wednesday-oxidize"
readme = "README.md"

[dependencies]
