[package]
name = "vm"
version = "0.1.0"
edition = "2021"

[metadata]
license = "MIT"
description = "A general purpose virtual machine"
homepage = "https://github.com/windows-fryer/wednesday-oxidize"
repository = "https://github.com/windows-fryer/wednesday-oxidize"
readme = "README.md"

[dependencies]
