[package]
name = "vm-cli"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "Wednesday virtual machine cli tool"
homepage = "https://github.com/windows-fryer/wednesday-oxidize"
repository = "https://github.com/windows-fryer/wednesday-oxidize"
readme = "README.md"

[dependencies]
vm = { path = "../vm" }